#!/usr/bin/env bash
# This script runs indefinitely and reacts to SIGTERM with a custom message

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
